version: '3'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - '3000:3000'

    environment:
      - PORT=3000
      - NODE_ENV=production
    command: npm run start
